### ISSUE TITLE
Can't bridge by channel

### ISSUE THREAD

**Issue by amalon** [mymindstorm/matrix-appservice-mumble#12]
When channels is set in mumble-config.yaml, no messages are relayed from mumble. It appears that the UserTextMessage event's message.channels[0] has the correct id etc but the name is just "", so it never matches the specified channel names. TBH I'm not sure whether this is a murmur issue (I'm using 1.3.0-7 on archlinux) or a bridge issue.

**Comment by mymindstorm** [comment]
Channel support is really bad right now. That option is for Mumble channels.

**Comment by amalon** [comment]
Heh, I just had a hack around this morning and got the config channels to filter properly both ways (getting the room list from the server using ChannelQuery where it returns both name and id for each), so even matrix messages go to a subset of mumble channels, but then saw you've done some work on it, probably much cleaner than my hacking anyway :-)
I'll take a look

**Comment by amalon** [comment]
FWIW this is what I had:
https://github.com/amalon/matrix-appservice-mumble/commit/c7350903efe745c677855724ce3106b95410879a

**Comment by mymindstorm** [comment]
The state of this codebase is pretty hacky anyway, I don't mind at all. I definitely don't deserve these commit messages anyway, just look at mine. 

There are properly generated typescript bindings for the GRPC client in master, it should be easier to write the mumble side of things now. Note that it will crash when it tries to connect until 693d55665c0e15a083a9081763020799bf41d570 is in master because of what is probably a bug with grpc_tools_node_protoc.

There is a room for the bridge at #mumble-bridge@evermiss.net, it's pretty quiet but it would be nice if you could join.
